name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build Tailwind
        run: npm run build

      - name: Prepare assets from node_modules
        run: |
          mkdir -p build/assets
          cp -R node_modules/soft-ui-design-system/assets/* build/assets/
          # Overlay any repo-provided assets (e.g., custom images)
          if [ -d assets ]; then cp -R assets/* build/assets/; fi

      - name: Prepare static site
        run: |
          mkdir -p build
          # Copy all top-level HTML pages and the compiled CSS dir
          cp -r *.html dist build/
          # Include pretty-URL directories (e.g., solutions/ -> /solutions/)
          if [ -d solutions ]; then cp -R solutions build/; fi
          # Ensure Jekyll doesn’t interfere with static files
          if [ -f .nojekyll ]; then cp .nojekyll build/; else touch build/.nojekyll; fi
          # Keep dist/ in place so the CSS link works:
          #   <link rel="stylesheet" href="./dist/output.css" />
          # assets/ is already added from node_modules in the previous step

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
